name: install gems

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dependencies-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run a one-line script
        run: echo Hello, world!
